import fs from "fs";
import path from "path";
import { readJson } from "./store";
import { readGitConfig } from "./git-auth";
import { checkInstallation, readConfig as readJiraConfig } from "./jira-cli";

const DATA_DIR = path.resolve(process.cwd(), "work-trees");
const FILE_PATH = path.join(DATA_DIR, "claude-permissions.json");

const MARKER_START = "<!-- AUTO-GENERATED BY WORKTREE HANDLER — DO NOT EDIT THIS SECTION -->";
const MARKER_END = "<!-- END AUTO-GENERATED -->";

interface PermissionsData {
  default: string[];
  [taskNo: string]: string[];
}

/* ── Read / Write permissions template ──────────────────── */

export function readPermissions(): PermissionsData {
  if (!fs.existsSync(FILE_PATH)) {
    return { default: [] };
  }
  try {
    return JSON.parse(fs.readFileSync(FILE_PATH, "utf-8"));
  } catch {
    return { default: [] };
  }
}

export function writePermissions(
  taskNo: string | undefined,
  rules: string[],
): void {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }

  const data = readPermissions();
  const key = !taskNo || taskNo === "default" ? "default" : taskNo;
  const cleaned = rules.map((r) => r.trim()).filter(Boolean);

  if (cleaned.length === 0) {
    if (key === "default") {
      data.default = [];
    } else {
      delete data[key];
    }
  } else {
    data[key] = cleaned;
  }

  fs.writeFileSync(FILE_PATH, JSON.stringify(data, null, 2), "utf-8");
}

/* ── Permission prompt generation ─────────────────────────── */

export function generatePermissionPrompt(taskNo: string): string {
  const lines: string[] = [];
  lines.push(MARKER_START);
  lines.push("## Available Tools & Permissions");
  lines.push("");

  // Jira section
  try {
    const jiraStatus = checkInstallation();
    if (jiraStatus.installed) {
      const jiraConfig = readJiraConfig();
      lines.push("### Jira CLI");
      lines.push(`- jira-cli installed${jiraStatus.version ? ` (${jiraStatus.version})` : ""}`);
      if (jiraConfig) {
        lines.push(`- Server: ${jiraConfig.server}`);
        lines.push(`- Project: ${jiraConfig.projectKey}`);
      }
      lines.push("- Jira 이슈 조회 시 WebFetch 대신 `jira issue view DV-XXX` 사용할 것");
      lines.push("");
    }
  } catch {
    // Skip jira section on error
  }

  // Git section
  try {
    const gitConfig = readGitConfig();
    if (gitConfig) {
      lines.push("### Git");
      if (gitConfig.provider) lines.push(`- Provider: ${gitConfig.provider}`);
      if (gitConfig.username) lines.push(`- Username: ${gitConfig.username}`);
      if (gitConfig.sshKeyPath) lines.push(`- SSH key configured: ${gitConfig.sshKeyPath}`);
      lines.push("");
    }
  } catch {
    // Skip git section on error
  }

  // Permissions section
  const data = readPermissions();
  const merged = [...(data.default || []), ...(data[taskNo] || [])];
  if (merged.length > 0) {
    lines.push("### Allowed Permissions");

    // Group by category
    const bash: string[] = [];
    const web: string[] = [];
    const tools: string[] = [];

    for (const rule of merged) {
      if (rule.startsWith("Bash(")) {
        // Extract command name: Bash(git add:*) → git add
        const match = rule.match(/^Bash\((.+?)(?::.*?)?\)$/);
        if (match) bash.push(match[1]);
      } else if (rule.startsWith("WebFetch(") || rule === "WebSearch") {
        web.push(rule);
      } else {
        tools.push(rule);
      }
    }

    if (bash.length > 0) lines.push(`- Bash: ${bash.join(", ")}`);
    if (tools.length > 0) lines.push(`- Tools: ${tools.join(", ")}`);
    if (web.length > 0) lines.push(`- Web: ${web.join(", ")}`);
    lines.push("");
  }

  lines.push(MARKER_END);
  return lines.join("\n");
}

function writePermissionsMd(worktreePath: string, prompt: string): void {
  const claudeDir = path.join(worktreePath, ".claude");
  fs.mkdirSync(claudeDir, { recursive: true });
  fs.writeFileSync(path.join(claudeDir, "permissions.md"), prompt + "\n", "utf-8");
}

/* ── Apply to worktree ──────────────────────────────────── */

export function applyToWorktree(
  taskNo: string,
  worktreePath: string,
): void {
  const data = readPermissions();
  const merged = [...(data.default || []), ...(data[taskNo] || [])];

  // Write .claude/settings.local.json
  if (merged.length > 0) {
    const claudeDir = path.join(worktreePath, ".claude");
    const settingsFile = path.join(claudeDir, "settings.local.json");

    let settings: { permissions?: { allow?: string[] }; [k: string]: unknown } = {};
    if (fs.existsSync(settingsFile)) {
      try {
        settings = JSON.parse(fs.readFileSync(settingsFile, "utf-8"));
      } catch {
        settings = {};
      }
    }

    const existing = settings.permissions?.allow ?? [];
    const allRules = [...new Set([...existing, ...merged])];
    settings.permissions = { ...settings.permissions, allow: allRules };

    fs.mkdirSync(claudeDir, { recursive: true });
    fs.writeFileSync(settingsFile, JSON.stringify(settings, null, 2), "utf-8");
  }

  // Write .claude/permissions.md prompt
  const prompt = generatePermissionPrompt(taskNo);
  writePermissionsMd(worktreePath, prompt);
}

export function applyToAllWorktrees(): void {
  const worktrees = readJson("active.json") as { taskNo: string; path: string }[];

  for (const wt of worktrees) {
    if (wt.path) {
      applyToWorktree(wt.taskNo, wt.path);
    }
  }
}
